# Generated by Django 5.2.4 on 2025-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('meetup', 'Meetup')], default='workshop', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='registered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
