# Generated by Django 5.2.4 on 2025-07-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_event_category_event_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_at',
        ),
    ]
